URL = "http://127.0.0.1:50359/"
DEFAULT_TIMEZONE = "PST"
DEFAULT_DATE = "2000-01-01 00:00:00"
DEFAULT_CLIMATE = "los angeles, ca"
DEFAULT_MODULE_NAMES = ["Power Flow", "Residential", "Market", "Wholesale",
            "Network", "Generators"]
DEFAULT_SCHEMATIC_TYPE = "DISTRIBUTION"
DEFAULT_MAP_TYPE = "POLITICAL"
DEFAULT_LAYOUT_TYPE = "MANUAL"
